import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Outfit } from 'next/font/google';
import 'animate.css';


const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
  weight: ['400', '500', '700'], // Poids à inclure
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
           <body className={`${outfit.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
